"""Add answers 1:n

Revision ID: 2ea2f09b5fc3
Revises: e22aabd22a91
Create Date: 2021-01-08 22:13:58.035680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea2f09b5fc3'
down_revision = 'e22aabd22a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('ref_count', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'question', sa.Column('ref_count', sa.Integer(), nullable=True))
    op.drop_column(u'question', 'answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'question', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column(u'question', 'ref_count')
    op.drop_table('answer')
    # ### end Alembic commands ###
