"""change data type

Revision ID: 4b4b5f2f9f0e
Revises: 4cbb8b3b692a
Create Date: 2021-04-27 16:26:59.442668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4b5f2f9f0e'
down_revision = '4cbb8b3b692a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('author', sa.Text(), nullable=True))
    op.drop_column('answer', 'added_by')
    op.add_column('question', sa.Column('author', sa.Text(), nullable=True))
    op.drop_column('question', 'asked_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('asked_by', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('question', 'author')
    op.add_column('answer', sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('answer', 'author')
    # ### end Alembic commands ###
