"""Changed relationships

Revision ID: 4cbb8b3b692a
Revises: 966b5d1bdc08
Create Date: 2021-04-27 16:12:51.332672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbb8b3b692a'
down_revision = '966b5d1bdc08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'answer_added_by_fkey', 'answer', type_='foreignkey')
    op.add_column('question', sa.Column('asked_by', sa.Text(), nullable=True))
    op.drop_constraint(u'question_expert_id_fkey', 'question', type_='foreignkey')
    op.drop_constraint(u'question_asked_by_id_fkey', 'question', type_='foreignkey')
    op.drop_column('question', 'expert_id')
    op.drop_column('question', 'asked_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('asked_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('expert_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'question_asked_by_id_fkey', 'question', 'user', ['asked_by_id'], ['id'])
    op.create_foreign_key(u'question_expert_id_fkey', 'question', 'user', ['expert_id'], ['id'])
    op.drop_column('question', 'asked_by')
    op.create_foreign_key(u'answer_added_by_fkey', 'answer', 'user', ['added_by'], ['id'])
    # ### end Alembic commands ###
