"""Add tags table

Revision ID: 966b5d1bdc08
Revises: 2ea2f09b5fc3
Create Date: 2021-04-02 19:32:08.189296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966b5d1bdc08'
down_revision = '2ea2f09b5fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_question_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_question_map')
    op.drop_table('tag')
    # ### end Alembic commands ###
