"""add vector index

Revision ID: 9f526487c749
Revises: 523be21c1439
Create Date: 2021-10-12 13:27:19.527109

"""
from alembic import op
import sqlalchemy as sa
from flask_qa import models


# revision identifiers, used by Alembic.
revision = '9f526487c749'
down_revision = '523be21c1439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecture', sa.Column('__ts_vector__', models.TSVector(), sa.Computed(u"to_tsvector('english', text)", persisted=True), nullable=True))
    op.create_index('ix_lecture___ts_vector__', 'lecture', ['__ts_vector__'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lecture___ts_vector__', table_name='lecture')
    op.drop_column('lecture', '__ts_vector__')
    # ### end Alembic commands ###
