"""Initial migration.

Revision ID: e22aabd22a91
Revises: 
Create Date: 2021-01-08 20:57:41.564682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22aabd22a91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('question', sa.Column('updated_on', sa.DateTime(), server_default=sa.text(u'(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('user', sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('user', sa.Column('updated_on', sa.DateTime(), server_default=sa.text(u'(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_on')
    op.drop_column('user', 'created_on')
    op.drop_column('question', 'updated_on')
    op.drop_column('question', 'created_on')
    # ### end Alembic commands ###
